checks:
  php: true

build:
  image: default-bionic
  environment:
    php: 8.1.2
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

tools:
  php_code_sniffer:
    enabled: true
    config:
      standard: PSR12
